### ISSUE TITLE
[ Bug ] Locally downloaded songs fail to play, but stream successfully after removal

### ISSUE THREAD

**Issue by SindreKjelsrud** [kepelet/flo#35]
I can stream the song from the album perfectly fine, but the moment I download it for offline usage it won't play anymore. It won't play when downloaded for offline usage and even not when streamed, unless I remove it from local storage.

**Comment by faultables** [comment]
coincidently i'm fixing the "download -> music can't be downloaded -> download should fail" issue from my todo list, and i think the bug is related to this? my condition is when i try to download a track but Navidrome doesn't have permission to read the local track and the album is in the "download" tab but can't do anything with it (because the track is not there)

**Comment by SindreKjelsrud** [comment]
It seems this has been fixed in v.1.6! 🎉

**Comment by faultables** [comment]
> It seems this has been fixed in v.1.6! 🎉 Should this issue just be closed then?

great! we can reopen this issue later if the problem is back
